### PR TITLE
Car rental create and get operations

### PR DESCRIPTION
**Pull request by PukarSubedi01**

### CODE REVIEW

**Review by iambissnuu — APPROVED** [review]

**Comment by rohanudas97** [comment]
nice

**Review by rohanudas97 — APPROVED** [review]
Good job pukar

**Comment by bypillaraghu** [comment]
Good work

**Comment by durapd** [comment]
h

**Review by durapd — APPROVED** [review]
pukar bhai good job

**Review by bypillaraghu — COMMENTED** [review]
GW

**Pull request merged**
